#!/usr/bin/env python3
"""Turn `doc/wren/results.json` into the pages under `doc/wren/`.

    tools/report-tests.py

One index plus one page per top-level group. The split is by group because that
is how upstream organises the suite and because a single 898-row table is a file
nobody reads — whereas "core/list is 40 of 41" is a sentence somebody acts on.

**Passing tests are counted, not listed.** A page that lists nine hundred passes
buries the dozen failures that are the reason to look. Every failure is listed in
full, with the first divergence, because that is the actionable part.
"""

import json
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOC = ROOT / "doc" / "wren"

STATUS_ORDER = ["fail", "crash", "timeout", "skip", "pass"]

# Groups that are not graded, and why.
#
# **`api` is out of scope by decision, not by difficulty.** Those tests are
# paired with C files that register foreign methods, so they exercise the
# embedding API rather than the language -- reachable only by compiling the C
# half into the port. Worth doing eventually for an embedded VM; not worth
# blocking the language on.
#
# `benchmark` is timing rather than correctness, and `unit` is C-level tests
# upstream runs on the host -- it holds no `.wren` files at all.
OUT_OF_SCOPE = {
    "api": "the embedding API -- needs the paired C harness compiled in",
    "benchmark": "timing, not correctness -- see the benchmark table",
    "unit": "C-level tests upstream runs on the host; no .wren files",
}


# Why each known failure fails, and whose fault it is.
#
# **Kept here rather than in prose** so it is regenerated with every run: a
# hand-written list of known failures is one that quietly describes last month's
# run. A test that starts passing simply stops appearing; one that starts
# failing shows up as `unclassified` and demands an answer.
#
# The categories matter more than the individual entries:
#
#   device    a real limit of this part -- the most interesting outcome, and
#             the thing the Rust implementation is measured against
#   harness   this console cannot express the test; not Wren's problem
#   upstream  Wren behaves differently here than its own suite expects
#   flaky     passes and fails between runs; a measurement problem
KNOWN = {
    "language/deeply_nested_gc.wren": (
        "device", "reboots the board -- deep GC nesting exhausts the stack"),
    "language/many_reallocations.wren": (
        "device", "reboots the board -- exhausts the heap"),
    "limit/many_constants.wren": (
        "harness", "the source is 513 KB; the board has 512 KB of RAM in total"),
    "limit/reuse_constants.wren": (
        "harness", "the source is 513 KB; the board has 512 KB of RAM in total"),
    "limit/many_globals.wren": (
        "harness", "the source is 1.5 MB; three times the board's entire RAM"),
    "limit/too_many_constants.wren": (
        "harness", "needs the 513 KB source above to reach the limit it tests"),
    "language/variable/too_many_locals.wren": (
        "harness", "needs more source than the console can carry to hit the limit"),
    "language/module/relative_import/relative_import.wren": (
        "harness", "needs a resolveModuleFn: nested `./x` is relative to the "
                   "importer, and the registry is keyed on the literal string"),
    "meta/get_module_variables.wren": (
        "harness", "inspects a module by name; the console registers modules "
                   "under the import string, not a resolved path"),
    "core/fiber/yield_from_import.wren": (
        "harness", "imports and yields across the module boundary"),
}


def group_of(test: str) -> str:
    return test.split("/")[0]


def subgroup_of(test: str) -> str:
    parts = test.split("/")
    return "/".join(parts[:2]) if len(parts) > 2 else parts[0]


def bar(passed: int, total: int, width: int = 24) -> str:
    if total == 0:
        return ""
    filled = round(width * passed / total)
    return "█" * filled + "░" * (width - filled)


def main():
    data = json.loads((DOC / "results.json").read_text())
    results = data["results"]
    meta = data.get("meta", {})

    by_group = defaultdict(list)
    for row in results:
        by_group[group_of(row["test"])].append(row)

    # --- the index --------------------------------------------------------
    lines = [
        "# Upstream Wren's test suite, on the ESP32-C6",
        "",
        "Generated by `tools/report-tests.py` from a run of `tools/run-tests.py`.",
        "**Do not edit by hand** — the next run overwrites it.",
        "",
        "This is upstream's own suite, unmodified, driven over the serial console",
        "against `ports/esp32c6-wren`. Every test is sent whole between `.run` and",
        "`.end` and scored against the `// expect:` comments the file already",
        "carries, so \"passes the suite\" means here what it means upstream.",
        "",
        "It exists for two reasons. It says how much of Wren actually works on this",
        "part, which is not a given — and it is the yardstick the Rust",
        "implementation will be held to, one group at a time.",
        "",
    ]

    if meta:
        lines += ["| | |", "|---|---|"]
        for key, value in meta.items():
            lines.append(f"| {key} | {value} |")
        lines.append("")

    # **The score is over the language groups only.** Mixing in `api` would
    # report the embedding harness as a language failure, and mixing in
    # `benchmark` would report a slow machine as a wrong one.
    in_scope = [r for r in results
                if group_of(r["test"]) not in OUT_OF_SCOPE and r["status"] != "skip"]
    passed = sum(1 for r in in_scope if r["status"] == "pass")
    failed = sum(1 for r in in_scope if r["status"] == "fail")
    timed_out = sum(1 for r in in_scope if r["status"] == "timeout")
    crashed = sum(1 for r in in_scope if r["status"] == "crash")
    rate = (passed / len(in_scope) * 100) if in_scope else 0.0

    lines += [
        "## The language",
        "",
        f"**{passed} of {len(in_scope)} pass — {rate:.1f}%.**",
        "",
        f"- {failed} failed",
        f"- {timed_out} timed out",
        f"- **{crashed} rebooted the board** — a footprint finding, not a correctness one",
        "",
        "Over `core`, `language`, `limit`, `meta`, `random` and `regression` —",
        "the groups that test the language itself. See below for what is excluded",
        "and why.",
        "",
        "## By group",
        "",
        "| group | passed | | notes |",
        "|---|---|---|---|",
    ]

    for group in sorted(by_group):
        rows = by_group[group]
        graded_rows = [r for r in rows if r["status"] != "skip"]
        group_passed = sum(1 for r in graded_rows if r["status"] == "pass")
        note = OUT_OF_SCOPE.get(group, "")
        marker = " *(not scored)*" if group in OUT_OF_SCOPE else ""
        lines.append(
            f"| [`{group}`]({group}.md){marker} | {group_passed}/{len(graded_rows)} | "
            f"`{bar(group_passed, len(graded_rows))}` | {note} |"
        )

    lines += ["", "## The pages",
              "",
              "| | |",
              "|---|---|",
              "| [`all-tests.md`](all-tests.md) | every test, one row, failures first |",
              "| `<group>.md` | one group's summary and its failures |",
              "| `output/<group>.md` | **what the board printed, test by test** |",
              "",
              "## What a failure here means", "",
              "A failure is one of three things, and the pages below say which:",
              "",
              "* **Wren does not support it on this part** — a real limitation, and the",
              "  most interesting outcome.",
              "* **The harness cannot express it** — `api/` tests call into C, and",
              "  `// stdin:` tests need input this console does not feed.",
              "* **The board ran out of something** — memory or time. Those show as",
              "  timeouts and are a footprint finding rather than a correctness one.",
              ""]

    # --- known failures, classified ---------------------------------------
    problems = [r for r in results
                if r["status"] in ("fail", "timeout", "crash")
                and group_of(r["test"]) not in OUT_OF_SCOPE]
    if problems:
        by_category = defaultdict(list)
        for row in problems:
            category, why = KNOWN.get(row["test"], ("unclassified", row["detail"]))
            by_category[category].append((row, why))

        lines += ["", "## Known failures", "",
                  f"{len(problems)} of the language suite does not pass. They are not",
                  "equivalent, and lumping them into one number would hide the only",
                  "ones that say something about Wren.", ""]

        headings = {
            "device": ("A real limit of this part",
                       "The most interesting outcome: Wren does something here that this "
                       "hardware cannot survive. These are the numbers the Rust "
                       "implementation is measured against, and they should **not** be "
                       "made to pass."),
            "upstream": ("Wren behaves differently here",
                         "The VM disagrees with its own test suite on this part."),
            "harness": ("This console cannot express the test",
                        "Not Wren's problem. A test that needs more source than the "
                        "board has memory for, or a facility this port does not "
                        "provide."),
            "flaky": ("Inconsistent between runs",
                      "A measurement problem rather than a result."),
            "unclassified": ("Not yet explained",
                             "**These need looking at.** A failure with no explanation "
                             "is an open question, not a known failure."),
        }
        for category in ("device", "upstream", "unclassified", "harness", "flaky"):
            entries = by_category.get(category)
            if not entries:
                continue
            title, blurb = headings[category]
            lines += [f"### {title} ({len(entries)})", "", blurb, "",
                      "| test | why |", "|---|---|"]
            for row, why in sorted(entries, key=lambda e: e[0]["test"]):
                lines.append(f"| `{row['test']}` | {why} |")
            lines.append("")

    (DOC / "README.md").write_text("\n".join(lines) + "\n")

    # --- one page per group ----------------------------------------------
    for group, rows in sorted(by_group.items()):
        by_sub = defaultdict(list)
        for row in rows:
            by_sub[subgroup_of(row["test"])].append(row)

        graded_rows = [r for r in rows if r["status"] != "skip"]
        passed = sum(1 for r in graded_rows if r["status"] == "pass")

        page = [
            f"# `{group}`",
            "",
            "Generated by `tools/report-tests.py`. **Do not edit by hand.**",
            "",
            f"**{passed} of {len(graded_rows)} graded tests pass.**",
            "",
            "| area | passed | |",
            "|---|---|---|",
        ]
        for sub in sorted(by_sub):
            sub_graded = [r for r in by_sub[sub] if r["status"] != "skip"]
            sub_passed = sum(1 for r in sub_graded if r["status"] == "pass")
            page.append(
                f"| `{sub}` | {sub_passed}/{len(sub_graded)} | "
                f"`{bar(sub_passed, len(sub_graded), 16)}` |"
            )

        problems = [r for r in rows if r["status"] in ("fail", "timeout", "crash")]
        if problems:
            page += ["", f"## Failures ({len(problems)})", "",
                     "| test | status | first divergence |", "|---|---|---|"]
            for row in sorted(problems, key=lambda r: r["test"]):
                detail = row["detail"].replace("|", "\\|")
                page.append(f"| `{row['test']}` | {row['status']} | {detail} |")

        skipped = [r for r in rows if r["status"] == "skip"]
        if skipped:
            page += ["", f"## Skipped ({len(skipped)})", "",
                     "Upstream marks these `// nontest` or `// skip:`; they are not",
                     "graded here either.", "",
                     "| test | why |", "|---|---|"]
            for row in sorted(skipped, key=lambda r: r["test"]):
                page.append(f"| `{row['test']}` | {row['detail']} |")

        page.append("")
        (DOC / f"{group}.md").write_text("\n".join(page) + "\n")

        # --- every test's output, one by one ------------------------------
        #
        # **Separate from the summary on purpose.** The group page is for
        # deciding what to fix; this is the record of what the board actually
        # said, which is what the Rust implementation gets compared against line
        # by line. Mixing them would make the first unreadable.
        detail_lines = [
            f"# `{group}` — every test's output",
            "",
            "Generated by `tools/report-tests.py`. **Do not edit by hand.**",
            "",
            "What the board printed for each test, in suite order. `expected` comes",
            "from the file's own `// expect:` comments; `got` is what came back",
            "between the run markers.",
            "",
        ]
        for row in sorted(rows, key=lambda r: r["test"]):
            mark = {"pass": "✓", "fail": "✗", "crash": "💥",
                    "timeout": "⏱", "skip": "—"}[row["status"]]
            detail_lines += [f"## {mark} `{row['test']}`", ""]

            if row["status"] == "skip":
                detail_lines += [f"Skipped: {row['detail']}", ""]
                continue

            if row.get("expect_compile_error"):
                detail_lines.append("Expects a **compile error**.")
            if row.get("expect_runtime_error"):
                detail_lines.append(
                    f"Expects a **runtime error**: `{row['expect_runtime_error']}`")

            expected_out = row.get("expected") or []
            got_out = row.get("got") or []

            if expected_out or got_out:
                detail_lines += ["", "| # | expected | got |", "|---|---|---|"]
                for i in range(max(len(expected_out), len(got_out))):
                    want = expected_out[i] if i < len(expected_out) else ""
                    have = got_out[i] if i < len(got_out) else ""
                    same = "" if want == have else " ⟵"
                    detail_lines.append(
                        f"| {i + 1} | `{want}` | `{have}`{same} |")
            if row["status"] != "pass" and row["detail"]:
                detail_lines += ["", f"**{row['status']}**: {row['detail']}"]
            detail_lines.append("")

        (DOC / "output").mkdir(parents=True, exist_ok=True)
        (DOC / "output" / f"{group}.md").write_text("\n".join(detail_lines) + "\n")

    # --- the flat overall report -----------------------------------------
    #
    # One row per test, everything, sorted worst-first. The group pages answer
    # "how is `core/list` doing"; this answers "what is broken" in one place and
    # is the thing to diff between two runs.
    overall = [
        "# Every test, one row each",
        "",
        "Generated by `tools/report-tests.py`. **Do not edit by hand.**",
        "",
        "Sorted failures first, then timeouts, then skips, then passes — so the",
        "top of the file is the work and the bottom is the evidence.",
        "",
        f"**{passed}/{len(in_scope)} of the language suite passes.**",
        "",
        "| status | test | detail |",
        "|---|---|---|",
    ]
    rank = {"fail": 0, "crash": 1, "timeout": 2, "skip": 3, "pass": 4}
    for row in sorted(results, key=lambda r: (rank[r["status"]], r["test"])):
        mark = {"pass": "✓ pass", "fail": "✗ **fail**", "crash": "💥 **crash**",
                "timeout": "⏱ timeout", "skip": "— skip"}[row["status"]]
        detail = (row["detail"] or "").replace("|", "\\|")
        link = f"output/{group_of(row['test'])}.md"
        overall.append(f"| {mark} | [`{row['test']}`]({link}) | {detail} |")
    overall.append("")
    (DOC / "all-tests.md").write_text("\n".join(overall) + "\n")

    print(f"written: doc/wren/README.md, all-tests.md, "
          f"{len(by_group)} group pages and {len(by_group)} output pages")


if __name__ == "__main__":
    main()
