//! Measure this implementation against Wren's own language documentation.
//!
//!     cargo run -p wren --example conformance
//!
//! **The report is generated by running the snippets, not written by hand.**
//! A conformance table maintained by editing is a table that drifts the first
//! time somebody fixes something and forgets to update it. Every row here is a
//! program that just ran, and its status is what actually happened.
//!
//! The chapters and their sections follow `vendor/wren/doc/site/*.markdown`,
//! which is the documentation published at <https://wren.io>, so a row that
//! says "missing" points at a specific paragraph of the spec.

use std::fmt::Write as _;

/// What a probe is supposed to do.
enum Expect {
    /// Print exactly this.
    Output(&'static str),
    /// Fail to compile or run. Some of the spec is about what is *rejected*.
    Error,
}

struct Probe {
    chapter: &'static str,
    feature: &'static str,
    source: &'static str,
    expect: Expect,
}

const fn out(
    chapter: &'static str,
    feature: &'static str,
    source: &'static str,
    expect: &'static str,
) -> Probe {
    Probe { chapter, feature, source, expect: Expect::Output(expect) }
}

const fn bad(chapter: &'static str, feature: &'static str, source: &'static str) -> Probe {
    Probe { chapter, feature, source, expect: Expect::Error }
}

fn probes() -> Vec<Probe> {
    vec![
        // --- syntax ---------------------------------------------------------
        out("Syntax", "Line comments", "// a comment\nSystem.print(1)", "1\n"),
        out("Syntax", "Block comments", "/* a\ncomment */\nSystem.print(1)", "1\n"),
        out("Syntax", "Nested block comments", "/* a /* b */ c */\nSystem.print(1)", "1\n"),
        out("Syntax", "Identifiers", "var camelCase = 1\nSystem.print(camelCase)", "1\n"),
        out("Syntax", "Newline as separator", "var a = 1\nvar b = 2\nSystem.print(a + b)", "3\n"),
        out(
            "Syntax",
            "Newlines ignored after operators",
            "System.print(1 +\n2)",
            "3\n",
        ),
        out("Syntax", "Blocks", "{\n  System.print(1)\n}", "1\n"),
        out(
            "Syntax",
            "Precedence and associativity",
            "System.print(2 + 3 * 4)\nSystem.print(10 - 4 - 3)",
            "14\n3\n",
        ),

        // --- values ---------------------------------------------------------
        out("Values", "Booleans", "System.print(true)\nSystem.print(false)", "true\nfalse\n"),
        out("Values", "Numbers", "System.print(1234)\nSystem.print(-12.34)", "1234\n-12.34\n"),
        out("Values", "Hexadecimal literals", "System.print(0xcaffe2)", "13303778\n"),
        out("Values", "Scientific notation", "System.print(1.5e3)", "1500\n"),
        out("Values", "Strings", "System.print(\"hi there\")", "hi there\n"),
        out(
            "Values",
            "Escaping",
            "System.print(\"a\\nb\")\nSystem.print(\"q\\\"q\")",
            "a\nb\nq\"q\n",
        ),
        out("Values", "Unicode escapes", "System.print(\"\\u0041\")", "A\n"),
        out("Values", "Byte escapes", "System.print(\"\\x41\")", "A\n"),
        out("Values", "Interpolation", "var n = 2\nSystem.print(\"n %(n) end\")", "n 2 end\n"),
        out(
            "Values",
            "Raw strings",
            "System.print(\"\"\"a \"quoted\" b\"\"\")",
            "a \"quoted\" b\n",
        ),
        out("Values", "Ranges", "System.print(1..3)\nSystem.print(1...3)", "1..3\n1...3\n"),
        out("Values", "Null", "System.print(null)", "null\n"),

        // --- lists ----------------------------------------------------------
        out("Lists", "List literals", "System.print([1, 2, 3])", "[1, 2, 3]\n"),
        out("Lists", "Accessing elements", "System.print([1, 2, 3][1])", "2\n"),
        out("Lists", "Negative indices", "System.print([1, 2, 3][-1])", "3\n"),
        out("Lists", "Slices and ranges", "System.print([1, 2, 3, 4][1..2])", "[2, 3]\n"),
        out("Lists", "Adding elements", "var l = [1]\nl.add(2)\nSystem.print(l)", "[1, 2]\n"),
        out("Lists", "Insert", "var l = [1, 3]\nl.insert(1, 2)\nSystem.print(l)", "[1, 2, 3]\n"),
        out("Lists", "Adding lists together", "System.print([1] + [2])", "[1, 2]\n"),
        out("Lists", "Removing elements", "var l = [1, 2]\nl.removeAt(0)\nSystem.print(l)", "[2]\n"),
        out("Lists", "Clear", "var l = [1, 2]\nl.clear()\nSystem.print(l.count)", "0\n"),
        out("Lists", "Count", "System.print([1, 2, 3].count)", "3\n"),

        // --- maps -----------------------------------------------------------
        out("Maps", "Map literals", "var m = {\"a\": 1}\nSystem.print(m[\"a\"])", "1\n"),
        out("Maps", "Empty map literal", "var m = {}\nSystem.print(m.count)", "0\n"),
        out("Maps", "Adding entries", "var m = {}\nm[\"k\"] = 1\nSystem.print(m[\"k\"])", "1\n"),
        out("Maps", "Missing key is null", "var m = {}\nSystem.print(m[\"nope\"])", "null\n"),
        out(
            "Maps",
            "containsKey",
            "var m = {\"a\": 1}\nSystem.print(m.containsKey(\"a\"))",
            "true\n",
        ),
        out("Maps", "Removing entries", "var m = {\"a\": 1}\nm.remove(\"a\")\nSystem.print(m.count)", "0\n"),
        out("Maps", "Keys and values", "var m = {\"a\": 1}\nSystem.print(m.keys.toList)", "[a]\n"),
        out(
            "Maps",
            "Iterating over the contents",
            "var m = {\"a\": 1}\nfor (e in m) System.print(e.key)",
            "a\n",
        ),

        // --- method calls ---------------------------------------------------
        out("Method calls", "Getters", "System.print(\"abc\".count)", "3\n"),
        out("Method calls", "Method with arguments", "System.print([1,2].contains(2))", "true\n"),
        out(
            "Method calls",
            "Setters",
            "class B {\n construct new() { _v = 0 }\n v { _v }\n v=(x) { _v = x }\n}\nvar b = B.new()\nb.v = 5\nSystem.print(b.v)",
            "5\n",
        ),
        out("Method calls", "Operators", "System.print(1 + 2)", "3\n"),
        out("Method calls", "Prefix operators", "System.print(-(3))\nSystem.print(!true)", "-3\nfalse\n"),
        out("Method calls", "Subscripts", "System.print([1,2][0])", "1\n"),
        out(
            "Method calls",
            "Subscript setters",
            "var l = [1]\nl[0] = 9\nSystem.print(l[0])",
            "9\n",
        ),
        out("Method calls", "Signature includes arity", "System.print(1.clamp(0, 2))", "1\n"),

        // --- control flow ---------------------------------------------------
        out("Control flow", "Truthiness", "System.print(!0)\nSystem.print(!null)", "false\ntrue\n"),
        out("Control flow", "If statements", "if (true) System.print(1)", "1\n"),
        out("Control flow", "Else", "if (false) System.print(1) else System.print(2)", "2\n"),
        out("Control flow", "Logical operators", "System.print(1 && 2)\nSystem.print(false || 3)", "2\n3\n"),
        out("Control flow", "Conditional operator ?:", "System.print(true ? 1 : 2)", "1\n"),
        out("Control flow", "While statements", "var i = 0\nwhile (i < 2) {\n System.print(i)\n i = i + 1\n}", "0\n1\n"),
        out("Control flow", "For over a range", "for (i in 1..2) System.print(i)", "1\n2\n"),
        out("Control flow", "For over a list", "for (x in [1,2]) System.print(x)", "1\n2\n"),
        out("Control flow", "Break statements", "for (i in 1..3) {\n if (i == 2) break\n System.print(i)\n}", "1\n"),
        out("Control flow", "Continue statements", "for (i in 1..3) {\n if (i == 2) continue\n System.print(i)\n}", "1\n3\n"),
        out(
            "Control flow",
            "The iterator protocol",
            "class Once {\n construct new() {}\n iterate(i) { i == null }\n iteratorValue(i) { 7 }\n}\nfor (x in Once.new()) System.print(x)",
            "7\n",
        ),

        // --- variables ------------------------------------------------------
        out("Variables", "Module scope", "var a = 1\nSystem.print(a)", "1\n"),
        out("Variables", "Block scope", "var a = 1\n{\n var a = 2\n System.print(a)\n}\nSystem.print(a)", "2\n1\n"),
        out("Variables", "Assignment", "var a = 1\na = 2\nSystem.print(a)", "2\n"),
        out("Variables", "Default null", "var a\nSystem.print(a)", "null\n"),
        bad("Variables", "Undefined variable is an error", "System.print(nope)"),

        // --- classes --------------------------------------------------------
        out("Classes", "Defining a class", "class A { construct new() {} }\nSystem.print(A)", "A\n"),
        out(
            "Classes",
            "Methods",
            "class A {\n construct new() {}\n greet() { \"hi\" }\n}\nSystem.print(A.new().greet())",
            "hi\n",
        ),
        out(
            "Classes",
            "Getters",
            "class A {\n construct new() {}\n v { 5 }\n}\nSystem.print(A.new().v)",
            "5\n",
        ),
        out(
            "Classes",
            "Operators",
            "class A {\n construct new() {}\n +(o) { 9 }\n}\nSystem.print(A.new() + 1)",
            "9\n",
        ),
        out(
            "Classes",
            "this",
            "class A {\n construct new() {}\n me { this }\n}\nvar a = A.new()\nSystem.print(a.me == a)",
            "true\n",
        ),
        out(
            "Classes",
            "Implicit this",
            "class A {\n construct new() {}\n a { 1 }\n b { a + 1 }\n}\nSystem.print(A.new().b)",
            "2\n",
        ),
        out(
            "Classes",
            "Constructors",
            "class A {\n construct new(x) { _x = x }\n x { _x }\n}\nSystem.print(A.new(3).x)",
            "3\n",
        ),
        out(
            "Classes",
            "Fields",
            "class A {\n construct new() { _f = 1 }\n f { _f }\n}\nSystem.print(A.new().f)",
            "1\n",
        ),
        bad(
            "Classes",
            "Fields are private",
            "class A {\n construct new() { _f = 1 }\n}\nSystem.print(A.new()._f)",
        ),
        out(
            "Classes",
            "Static members",
            "class A {\n static v { 7 }\n}\nSystem.print(A.v)",
            "7\n",
        ),
        out(
            "Classes",
            "Static fields",
            "class A {\n static bump {\n  __n = (__n == null) ? 1 : __n + 1\n  return __n\n }\n}\nSystem.print(A.bump)\nSystem.print(A.bump)",
            "1\n2\n",
        ),
        out(
            "Classes",
            "Inheritance",
            "class A {\n construct new() {}\n v { 1 }\n}\nclass B is A { construct new() { super() } }\nSystem.print(B.new().v)",
            "1\n",
        ),
        out(
            "Classes",
            "super",
            "class A {\n construct new() {}\n v { 1 }\n}\nclass B is A {\n construct new() { super() }\n v { super.v + 1 }\n}\nSystem.print(B.new().v)",
            "2\n",
        ),
        out(
            "Classes",
            "is operator",
            "class A { construct new() {} }\nSystem.print(A.new() is A)",
            "true\n",
        ),
        out("Classes", "type getter", "System.print(1.type)", "Num\n"),

        // --- functions ------------------------------------------------------
        out("Functions", "Creating a function", "var f = Fn.new { 1 }\nSystem.print(f.call())", "1\n"),
        out(
            "Functions",
            "Function parameters",
            "var f = Fn.new { |a, b| a + b }\nSystem.print(f.call(1, 2))",
            "3\n",
        ),
        out(
            "Functions",
            "Returning values",
            "var f = Fn.new {\n  return 4\n}\nSystem.print(f.call())",
            "4\n",
        ),
        out(
            "Functions",
            "Closures",
            "var n = 1\nvar f = Fn.new { n }\nn = 2\nSystem.print(f.call())",
            "2\n",
        ),
        out(
            "Functions",
            "Callable classes",
            "class A {\n construct new() {}\n call(x) { x * 2 }\n}\nSystem.print(A.new().call(3))",
            "6\n",
        ),
        out(
            "Functions",
            "Block arguments",
            "var l = []\n[1, 2].each { |x| l.add(x) }\nSystem.print(l)",
            "[1, 2]\n",
        ),
        out("Functions", "arity", "System.print(Fn.new { |a| a }.arity)", "1\n"),

        // --- concurrency ----------------------------------------------------
        out("Concurrency", "Creating fibers", "var f = Fiber.new { 1 }\nSystem.print(f.call())", "1\n"),
        out(
            "Concurrency",
            "Yielding",
            "var f = Fiber.new {\n  Fiber.yield(1)\n  Fiber.yield(2)\n}\nSystem.print(f.call())\nSystem.print(f.call())",
            "1\n2\n",
        ),
        out(
            "Concurrency",
            "Passing values",
            "var f = Fiber.new { |a| a * 2 }\nSystem.print(f.call(3))",
            "6\n",
        ),
        out(
            "Concurrency",
            "isDone",
            "var f = Fiber.new { 1 }\nf.call()\nSystem.print(f.isDone)",
            "true\n",
        ),
        out(
            "Concurrency",
            "Transferring control",
            // `transfer` does not come back -- that is the difference from
            // `call` -- so the printing has to happen inside the fiber.
            "var f = Fiber.new { System.print(1) }\nf.transfer()",
            "1\n",
        ),

        // --- error handling -------------------------------------------------
        out(
            "Error handling",
            "Creating runtime errors",
            "var f = Fiber.new { Fiber.abort(\"oops\") }\nSystem.print(f.try())",
            "oops\n",
        ),
        out(
            "Error handling",
            "Handling runtime errors",
            "var f = Fiber.new { 1/0 }\nf.try()\nSystem.print(\"survived\")",
            "survived\n",
        ),
        bad("Error handling", "Runtime errors abort", "1.nope"),
        out(
            "Error handling",
            "error getter",
            "var f = Fiber.new { Fiber.abort(\"x\") }\nf.try()\nSystem.print(f.error)",
            "x\n",
        ),

        // --- modularity -----------------------------------------------------
        out(
            "Modularity",
            "Importing",
            "import \"random\" for Random\nSystem.print(1)",
            "1\n",
        ),
        out(
            "Modularity",
            "Import with rename",
            "import \"random\" for Random as R\nSystem.print(1)",
            "1\n",
        ),
        out("Modularity", "meta module", "import \"meta\" for Meta\nSystem.print(1)", "1\n"),
    ]
}

fn main() {
    let probes = probes();
    let mut rows: Vec<(String, &'static str, &'static str, String, String)> = Vec::new();

    for probe in &probes {
        let mut vm = wren::Vm::new();
        let (status, note) = match (vm.interpret(probe.source), &probe.expect) {
            (Ok(()), Expect::Output(want)) => {
                if vm.output_str() == *want {
                    ("works", String::new())
                } else {
                    ("differs", format!("printed {:?}, spec says {:?}", vm.output_str(), want))
                }
            }
            (Ok(()), Expect::Error) => ("differs", "should have failed, did not".to_string()),
            (Err(error), Expect::Error) => {
                let _ = error;
                ("works", String::new())
            }
            (Err(error), Expect::Output(_)) => ("missing", error.message().to_string()),
        };
        rows.push((probe.chapter.to_string(), probe.feature, probe.source, status.to_string(), note));
    }

    let works = rows.iter().filter(|row| row.3 == "works").count();
    let differs = rows.iter().filter(|row| row.3 == "differs").count();
    let missing = rows.iter().filter(|row| row.3 == "missing").count();

    let mut page = String::new();
    let _ = writeln!(page, "# Wren conformance\n");
    let _ = writeln!(
        page,
        "**Generated by `cargo run -p wren --example conformance`. Do not edit by hand** —\n\
         every row is a program that was just run, and its status is what actually\n\
         happened. A table maintained by editing drifts the first time somebody fixes\n\
         something and forgets the doc.\n"
    );
    let _ = writeln!(
        page,
        "The chapters follow Wren's own documentation — `vendor/wren/doc/site/*.markdown`,\n\
         published at <https://wren.io> — so a `missing` row points at a specific\n\
         paragraph of the spec rather than at a vague gap.\n"
    );
    let _ = writeln!(page, "| | |");
    let _ = writeln!(page, "|---|---|");
    let _ = writeln!(page, "| probes | {} |", rows.len());
    let _ = writeln!(page, "| **works** | **{works}** |");
    let _ = writeln!(page, "| differs | {differs} |");
    let _ = writeln!(page, "| missing | {missing} |");
    let _ = writeln!(page);

    let _ = writeln!(page, "## By chapter\n");
    let _ = writeln!(page, "| chapter | works | differs | missing |");
    let _ = writeln!(page, "|---|---|---|---|");
    let mut chapters: Vec<&str> = Vec::new();
    for row in &rows {
        if !chapters.contains(&row.0.as_str()) {
            chapters.push(Box::leak(row.0.clone().into_boxed_str()));
        }
    }
    for chapter in &chapters {
        let mine: Vec<_> = rows.iter().filter(|row| row.0 == *chapter).collect();
        let w = mine.iter().filter(|row| row.3 == "works").count();
        let d = mine.iter().filter(|row| row.3 == "differs").count();
        let m = mine.iter().filter(|row| row.3 == "missing").count();
        let _ = writeln!(page, "| [{chapter}](#{}) | {w} | {d} | {m} |", anchor(chapter));
    }
    let _ = writeln!(page);

    for chapter in &chapters {
        let _ = writeln!(page, "## {chapter}\n");
        let _ = writeln!(page, "| feature | status | note |");
        let _ = writeln!(page, "|---|---|---|");
        for row in rows.iter().filter(|row| row.0 == *chapter) {
            let mark = match row.3.as_str() {
                "works" => "works",
                "differs" => "**differs**",
                _ => "**missing**",
            };
            let note = if row.4.is_empty() { "" } else { &row.4 };
            let _ = writeln!(page, "| {} | {mark} | {} |", row.1, escape(note));
        }
        let _ = writeln!(page);
    }

    let path = "doc/wren-rs/language.md";
    std::fs::create_dir_all("doc/wren-rs").ok();
    std::fs::write(path, page).expect("write the report");
    println!("{works} work, {differs} differ, {missing} missing, of {}", rows.len());
    println!("written: {path}");
}

fn anchor(chapter: &str) -> String {
    chapter.to_lowercase().replace(' ', "-")
}

fn escape(note: &str) -> String {
    note.replace('|', "\\|").replace('\n', " ")
}
