//! Emit a program's core library as Rust, to be compiled into its image.
//!
//!     cargo run --example freeze -- benchmarks/wrenc/fib.wrenc > core.rs
//!
//! **What this does.** It builds the VM a program's manifest implies --
//! exactly the one the firmware would build at start-up -- and then writes
//! that finished state out as `static` items: every class, its method table
//! already flattened, and the name of every method symbol. The firmware
//! compiles the result in and adopts it instead of building it in RAM.
//!
//! **Why a generator rather than a `const fn`.** A method table is indexed by
//! symbol, and symbols are numbered by the order `core::install` interns them
//! -- which depends on which `define` calls the manifest lets through. That is
//! a property of running the installer, not something the type system can
//! compute, so the honest way to get it is to run it and write down what
//! happened.
//!
//! The emitted module is checked against the crate it is compiled with; see
//! `FrozenCore::disagreement`.

use std::collections::BTreeMap;
use std::fmt::Write as _;

use wren::handle::ObjectId;
use wren::object::ObjectType;
use wren::Vm;

fn main() {
    let mut arguments = std::env::args().skip(1);
    let Some(path) = arguments.next() else {
        eprintln!("usage: freeze <program.wrenc>");
        std::process::exit(2);
    };

    let bytes = match std::fs::read(&path) {
        Ok(bytes) => bytes,
        Err(error) => {
            eprintln!("cannot read {path}: {error}");
            std::process::exit(1);
        }
    };
    let manifest = match wren::wrenc::manifest(&bytes) {
        Ok(manifest) => manifest,
        Err(error) => {
            eprintln!("{path} is not loadable: {}", error.message());
            std::process::exit(1);
        }
    };

    // The VM the firmware would otherwise build at start-up.
    let vm = Vm::with_manifest(&manifest);

    // Classes and strings, in handle order. `ids` walks each table in index
    // order, which is the order the handles were given out.
    let mut classes: BTreeMap<u32, ObjectId> = BTreeMap::new();
    let mut strings: BTreeMap<u32, ObjectId> = BTreeMap::new();
    for id in vm.heap.ids() {
        match ObjectType::from_tag(id.tag()) {
            Some(ObjectType::Class) => {
                classes.insert(id.index(), id);
            }
            Some(ObjectType::String) => {
                strings.insert(id.index(), id);
            }
            _ => {}
        }
    }

    // **The invariant the emitted indices rest on.** Every class is created by
    // allocating its name and then the class itself, and nothing else
    // allocates a string while the core is being built -- so string `i` is the
    // name of class `i`. If that ever stops being true the generated handles
    // would name the wrong strings, so it is checked here rather than assumed.
    if classes.len() != strings.len() {
        eprintln!(
            "cannot freeze: {} classes but {} strings -- something other than a \
             class name is being allocated during start-up, so a class's name is \
             no longer at its own index",
            classes.len(),
            strings.len()
        );
        std::process::exit(1);
    }
    for (index, id) in &classes {
        let class = vm.heap.class(*id).expect("a listed class must be reachable");
        if class.name.index() != *index || class.name.tag() != ObjectType::String.tag() {
            eprintln!(
                "cannot freeze: class {index} is named by string {} rather than its own index",
                class.name.index()
            );
            std::process::exit(1);
        }
    }

    let mut out = String::new();
    let stem = std::path::Path::new(&path)
        .file_stem()
        .map(|stem| stem.to_string_lossy().to_string())
        .unwrap_or_else(|| "program".to_string());

    // **Plain comments, not `//!`.** The emitted file is meant to be usable
    // either as a module of its own or through `include!`, and an inner doc
    // comment is a syntax error in the second case.
    writeln!(out, "// The core library for `{stem}`, built into the image.").unwrap();
    writeln!(out, "//").unwrap();
    writeln!(
        out,
        "// Generated by `cargo run --example freeze -- {path}`. Do not edit:"
    )
    .unwrap();
    writeln!(
        out,
        "// every index here was decided by running `core::install`, and editing"
    )
    .unwrap();
    writeln!(out, "// one by hand would dispatch to the wrong method.").unwrap();
    writeln!(out, "//").unwrap();
    writeln!(
        out,
        "// {} classes, {} method symbols, {} primitives.",
        classes.len(),
        vm.method_names.len(),
        vm.primitives.len()
    )
    .unwrap();
    writeln!(out, "//").unwrap();
    writeln!(
        out,
        "// Generated against this feature set, and only valid for a build with"
    )
    .unwrap();
    writeln!(
        out,
        "// the same one -- the primitive indices below are positions in the"
    )
    .unwrap();
    writeln!(out, "// sequence of `define` calls, which the features decide:").unwrap();
    writeln!(out, "//     core_full  {}", cfg!(feature = "core_full")).unwrap();
    writeln!(out, "//     nofp       {}", cfg!(feature = "nofp")).unwrap();
    writeln!(out, "//     f32        {}", cfg!(feature = "f32")).unwrap();
    writeln!(out).unwrap();
    writeln!(out, "use wren::frozen::FrozenCore;").unwrap();
    writeln!(out, "use wren::handle::ObjectId;").unwrap();
    writeln!(out, "use wren::object::{{ObjClass, ObjectType}};").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "/// String handle `index`, which names class `index`.").unwrap();
    writeln!(out, "const fn name_of(index: u32) -> ObjectId {{").unwrap();
    writeln!(
        out,
        "    ObjectId::tagged(ObjectType::String.tag(), index)"
    )
    .unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "const fn class(index: u32) -> ObjectId {{").unwrap();
    writeln!(out, "    ObjectId::tagged(ObjectType::Class.tag(), index)").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // The names, in class order.
    writeln!(
        out,
        "static CLASS_NAMES: [&str; {}] = [",
        classes.len()
    )
    .unwrap();
    for id in strings.values() {
        let text = vm
            .heap
            .string(*id)
            .and_then(wren::object::ObjString::as_str)
            .unwrap_or("?");
        writeln!(out, "    {text:?},").unwrap();
    }
    writeln!(out, "];").unwrap();
    writeln!(out).unwrap();

    // One method table per class. Emitted separately so each is its own
    // `static` and the class array stays readable.
    for (index, id) in &classes {
        let class = vm.heap.class(*id).expect("reachable");
        writeln!(
            out,
            "/// `{}`",
            vm.heap
                .string(class.name)
                .and_then(wren::object::ObjString::as_str)
                .unwrap_or("?")
        )
        .unwrap();
        write!(out, "static METHODS_{index}: [u32; {}] = [", class.methods.len()).unwrap();
        for (position, entry) in class.methods.iter().enumerate() {
            if position % 8 == 0 {
                write!(out, "\n    ").unwrap();
            }
            write!(out, "{entry}, ").unwrap();
        }
        writeln!(out, "\n];").unwrap();
    }
    writeln!(out).unwrap();

    writeln!(out, "static CLASSES: [ObjClass; {}] = [", classes.len()).unwrap();
    for (index, id) in &classes {
        let class = vm.heap.class(*id).expect("reachable");
        let superclass = match class.superclass {
            Some(parent) => format!("Some(class({}))", parent.index()),
            None => "None".to_string(),
        };
        let metaclass = match class.metaclass {
            Some(meta) => format!("Some(class({}))", meta.index()),
            None => "None".to_string(),
        };
        writeln!(
            out,
            "    ObjClass::frozen(name_of({index}), {superclass}, {metaclass}, &METHODS_{index}),"
        )
        .unwrap();
    }
    writeln!(out, "];").unwrap();
    writeln!(out).unwrap();

    writeln!(
        out,
        "static SYMBOLS: [&str; {}] = [",
        vm.method_names.len()
    )
    .unwrap();
    for symbol in 0..vm.method_names.len() {
        let name = vm.method_names.name(symbol).unwrap_or("?");
        writeln!(out, "    {name:?},").unwrap();
    }
    writeln!(out, "];").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "/// The core this program needs, and nothing else.").unwrap();
    writeln!(out, "pub static CORE: FrozenCore = FrozenCore {{").unwrap();
    writeln!(out, "    class_names: &CLASS_NAMES,").unwrap();
    writeln!(out, "    classes: &CLASSES,").unwrap();
    writeln!(out, "    symbols: &SYMBOLS,").unwrap();
    writeln!(out, "    primitives: {},", vm.primitives.len()).unwrap();
    writeln!(out, "}};").unwrap();

    print!("{out}");
}
